# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_cpc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TSG',
        ),
    ]
