# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_delete_tsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=7)),
                ('ano', models.IntegerField(default=0)),
                ('codcurso', models.IntegerField(default=0)),
                ('nomecurso', models.CharField(max_length=50)),
                ('ingressantes', models.IntegerField(default=0)),
                ('formados', models.IntegerField(default=0)),
                ('matriculados', models.IntegerField(default=0)),
                ('tsgtaxa', models.FloatField(default=0)),
                ('tsgcentro', models.FloatField(default=0)),
                ('tsgufsm', models.FloatField(default=0)),
                ('anoingresso', models.IntegerField(default=0)),
            ],
        ),
    ]
