# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_igc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPC_GERAL',
            fields=[
                ('area', models.CharField(default=b'', max_length=23, primary_key=True, serialize=False)),
                ('uf', models.CharField(default=b'', max_length=2)),
                ('regiao', models.IntegerField(default=0)),
                ('ano', models.IntegerField(default=0, null=True)),
                ('cpccontinuo', models.FloatField(default=0)),
                ('nc', models.FloatField(default=0)),
                ('nidd', models.FloatField(default=0)),
                ('nm', models.IntegerField(default=0, null=True)),
                ('nd', models.IntegerField(default=0, null=True)),
                ('nome_ies', models.CharField(default=b'', max_length=43)),
                ('sigla_ies', models.CharField(default=b'', max_length=4)),
                ('publica', models.IntegerField(default=0)),
                ('cat_adm', models.CharField(default=b'', max_length=7)),
                ('org_cad', models.CharField(default=b'', max_length=22)),
                ('municipio', models.CharField(default=b'', max_length=10)),
                ('nr', models.IntegerField(default=0, null=True)),
                ('no', models.IntegerField(default=0)),
                ('cpc_faixa', models.IntegerField(default=0, null=True)),
                ('nf', models.IntegerField(default=0, null=True)),
                ('codigo_curso', models.IntegerField(default=0)),
                ('na', models.IntegerField(default=0, null=True)),
                ('cpc_f2013', models.FloatField(default=0)),
                ('id_centro', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cpc',
            name='centro',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpc',
            name='cpc_antigo',
            field=models.CharField(default=b'', max_length=4),
        ),
    ]
