# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20160616_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpc',
            old_name='CPC_FAIXA',
            new_name='cpc_faixa',
        ),
    ]
