# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_auto_20160616_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpc',
            name='concluintes_inscritos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cpc',
            name='concluintes_participantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpc',
            name='concluintes_participantes_nota_enem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpc',
            name='num_docentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpc',
            name='num_matr_culas',
            field=models.IntegerField(default=0),
        ),
    ]
